# roles/base/tasks/additional.yml
---
- name: add repository location
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-6.rpm
  become: yes

- name: Install docker
  yum:
    name: docker-io
  become: yes

- name: yum update
  yum:
    name: '*'
    state: latest
  become: yes
